apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingressroute
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`traefik.com`)
    kind: Rule
    services:
    - name: traeefik-service
      port: 80